//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenServiceWCF_client_envoyer.GestionProjetReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GestionProjetReference.IGestionService")]
    public interface IGestionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GererProjet", ReplyAction="http://tempuri.org/IGestionService/GererProjetResponse")]
        void GererProjet(string code, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GererProjet", ReplyAction="http://tempuri.org/IGestionService/GererProjetResponse")]
        System.Threading.Tasks.Task GererProjetAsync(string code, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/RecupererProjet", ReplyAction="http://tempuri.org/IGestionService/RecupererProjetResponse")]
        string RecupererProjet(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/RecupererProjet", ReplyAction="http://tempuri.org/IGestionService/RecupererProjetResponse")]
        System.Threading.Tasks.Task<string> RecupererProjetAsync(string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionServiceChannel : ExamenServiceWCF_client_envoyer.GestionProjetReference.IGestionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionServiceClient : System.ServiceModel.ClientBase<ExamenServiceWCF_client_envoyer.GestionProjetReference.IGestionService>, ExamenServiceWCF_client_envoyer.GestionProjetReference.IGestionService {
        
        public GestionServiceClient() {
        }
        
        public GestionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GererProjet(string code, string description) {
            base.Channel.GererProjet(code, description);
        }
        
        public System.Threading.Tasks.Task GererProjetAsync(string code, string description) {
            return base.Channel.GererProjetAsync(code, description);
        }
        
        public string RecupererProjet(string code) {
            return base.Channel.RecupererProjet(code);
        }
        
        public System.Threading.Tasks.Task<string> RecupererProjetAsync(string code) {
            return base.Channel.RecupererProjetAsync(code);
        }
    }
}
